import { StyleSheet } from 'react-native';
export const colors = {
  red: '#B31325',
  ink: '#202329',
  muted: '#747981',
  border: '#ECEEF1',
  wash: '#F7F8FA',
  rose: '#FFF3F3',
  green: '#287258',
  white: '#FFFFFF',
};
export const s = StyleSheet.create({
  title: {
    fontSize: 30,
    lineHeight: 36,
    fontWeight: '700',
    color: colors.ink,
    letterSpacing: -0.8,
  },
  subtitle: { fontSize: 14, lineHeight: 22, color: colors.muted, marginTop: 8 },
  sectionTitle: { fontSize: 19, lineHeight: 25, fontWeight: '600', color: colors.ink },
  text: { fontSize: 15, lineHeight: 23, color: colors.ink },
  small: { fontSize: 12, lineHeight: 18, color: colors.muted },
  eyebrow: {
    fontSize: 10,
    lineHeight: 16,
    letterSpacing: 1.6,
    fontWeight: '700',
    color: colors.red,
  },
  card: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    padding: 20,
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  divider: { height: 1, backgroundColor: colors.border, marginVertical: 18 },
  input: {
    borderWidth: 1,
    borderColor: '#DFE2E6',
    borderRadius: 12,
    backgroundColor: colors.white,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 16,
    color: colors.ink,
    minHeight: 48,
  },
  label: { fontSize: 13, fontWeight: '600', color: colors.ink, marginBottom: 7 },
  stack: { gap: 18 },
});
