import { StyleSheet } from 'react-native';
import { colors as c } from '../ui/theme';
export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#FAFBFC' },
  shell: {
    flex: 1,
    flexDirection: 'row',
    maxWidth: 1280,
    width: '100%',
    alignSelf: 'center',
    backgroundColor: c.white,
  },
  sidebar: { width: 256, borderRightWidth: 1, borderColor: c.border, padding: 28, paddingTop: 33 },
  brand: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  brandMark: {
    backgroundColor: c.red,
    borderRadius: 7,
    width: 28,
    height: 31,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandText: { fontSize: 12, fontWeight: '900', lineHeight: 12, color: c.red, letterSpacing: -0.4 },
  sideItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 16,
    paddingHorizontal: 12,
    marginHorizontal: -12,
    borderRadius: 10,
    marginBottom: 6,
  },
  main: { flex: 1, minWidth: 0 },
  header: {
    minHeight: 76,
    paddingHorizontal: 22,
    paddingVertical: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: c.border,
    gap: 12,
  },
  profile: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    minHeight: 48,
    flex: 1,
    minWidth: 0,
  },
  contextChevron: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: c.wash,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scroll: { paddingTop: 26, paddingBottom: 32 },
  page: { maxWidth: 650, width: '100%', alignSelf: 'center' },
  dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: c.green },
  bottom: { borderTopWidth: 1, borderColor: c.border, backgroundColor: c.white },
  bottomInner: {
    flexDirection: 'row',
    height: 88,
    alignItems: 'center',
    maxWidth: 650,
    width: '100%',
    alignSelf: 'center',
    paddingHorizontal: 8,
  },
  navItem: { flex: 1, minHeight: 58, alignItems: 'center', justifyContent: 'center', gap: 6 },
  counter: { width: 78, alignItems: 'center', gap: 4, alignSelf: 'center', marginTop: -18 },
  counterPill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 63,
    minHeight: 30,
    paddingHorizontal: 7,
    gap: 3,
    backgroundColor: c.white,
    borderWidth: 1,
    borderColor: '#F1D6D9',
    borderRadius: 20,
  },
  plus: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: c.red,
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0px 4px 12px rgba(179,19,37,0.16)',
  },
  toast: {
    position: 'absolute',
    bottom: 105,
    alignSelf: 'center',
    maxWidth: '92%',
    paddingHorizontal: 18,
    paddingVertical: 12,
    backgroundColor: '#282C32',
    borderRadius: 12,
    zIndex: 100,
  },
});
