// Generated by npm run build:content. Edit sources.yaml, not this file.
import { sourceAssets } from './source-assets.generated';
export const lessonVideos: Record<string, { title: string; source: number }> = {
  "wheatley-crab": { title: "Wheatley Crab", source: sourceAssets["wheatley-crab"] },
};
