// Generated by npm run build:content. Edit sources.yaml, not this file.
export const sourceAssets: Record<string, number> = {
  "cik-multiday-voting": require("./global/documents/cik-08_06_2022_N_86_718_8.rtf"),
  "cik-voter-lists-2026": require("./global/documents/pril-6-66-9.1.docx"),
  "complaint-template": require("./global/documents/Жалоба.docx"),
  "fz67": require("./global/documents/fz-67.docx"),
  "fz67-2026-excerpts": require("./global/documents/fz67-2026-cited-articles.txt"),
  "wheatley-crab": require("./global/videos/Wheatley Crab.mp4"),
};
