import assert from 'node:assert/strict';
import { existsSync, realpathSync, statSync } from 'node:fs';
import { isAbsolute, relative, resolve } from 'node:path';

export function mergeSourceTables(documents, videos) {
  const sources = { ...documents };
  for (const [id, source] of Object.entries(documents))
    assert.notEqual(source.purpose, 'procedure-video', `Video ${id}: move its description to global/videos/sources.yaml`);
  for (const [id, source] of Object.entries(videos)) {
    assert.ok(!Object.hasOwn(sources, id), 'Duplicate source ID across documents and videos: ' + id);
    assert.equal(source.purpose, 'procedure-video', `Source ${id}: global/videos/sources.yaml accepts procedure-video entries`);
    sources[id] = source;
  }
  return sources;
}

export function generateSourceAssets(sources, root) {
  const files = new Map();
  const inside = (path) => {
    const part = relative(realpathSync(root), path);
    return part !== '..' && !part.startsWith('..\\') && !part.startsWith('../') && !isAbsolute(part);
  };
  for (const source of Object.values(sources)) {
    if (source.assetKey === null) continue;
    const authoredPath = source.file ?? `global/${source.purpose === 'procedure-video' ? 'videos' : 'documents'}/${source.name}`;
    assert.ok(!isAbsolute(authoredPath), `Source ${source.id}: file must be relative to src/content`);
    const target = resolve(root, authoredPath);
    assert.ok(inside(target), `Source ${source.id}: file escapes src/content`);
    assert.ok(existsSync(target) && statSync(target).isFile(), `Source ${source.id}: missing file ${authoredPath}`);
    assert.ok(inside(realpathSync(target)), `Source ${source.id}: file resolves outside src/content`);
    const path = './' + relative(root, target).replaceAll('\\', '/');
    assert.ok(!files.has(source.assetKey) || files.get(source.assetKey) === path,
      `Conflicting files for assetKey ${source.assetKey}`);
    files.set(source.assetKey, path);
  }
  const rows = [...files].sort(([a], [b]) => a.localeCompare(b))
    .map(([key, path]) => `  ${JSON.stringify(key)}: require(${JSON.stringify(path)}),`);
  return '// Generated by npm run build:content. Edit sources.yaml, not this file.\n' +
    'export const sourceAssets: Record<string, number> = {\n' + rows.join('\n') + '\n};\n';
}

export function lessonVideoSources(sources) {
  return Object.values(sources)
    .filter((source) => source.purpose === 'procedure-video' && source.assetKey !== null)
    .sort((a, b) => a.id.localeCompare(b.id))
    .map((source) => {
      assert.ok(source.mime.startsWith('video/'), `Video ${source.id}: expected a video MIME type`);
      return source;
    });
}

export function generateLessonVideos(sources) {
  const rows = lessonVideoSources(sources).map((source) =>
    `  ${JSON.stringify(source.id)}: { title: ${JSON.stringify(source.title)}, source: sourceAssets[${JSON.stringify(source.assetKey)}] },`);
  return '// Generated by npm run build:content. Edit sources.yaml, not this file.\n' +
    "import { sourceAssets } from './source-assets.generated';\n" +
    'export const lessonVideos: Record<string, { title: string; source: number }> = {\n' +
    rows.join('\n') + '\n};\n';
}
