example-city-2027:check-documents:
  id: example-city-2027:check-documents
  text: "EXAMPLE: check your observer documents."
  lawIds:
    - example-city-2027:example-law
  sourceIds: []
  media: []
example-city-2027:record-arrival:
  id: example-city-2027:record-arrival
  text: "EXAMPLE: record your arrival time."
  lawIds: []
  sourceIds: []
  media: []
example-city-2027:check-home-register:
  id: example-city-2027:check-home-register
  text: "EXAMPLE: check the home-voting register."
  lawIds:
    - example-city-2027:example-law
  sourceIds: []
  media: []
